Repository NovoNordisk-OpenSource/decentralized-tech-radar, pull requests merged in 2024-05, with the labels that each got.

#137 [5:12] Refactor: optimize style.css to reduce size and remove redundancy
  docs/dev_docs/script_file_dependencies.md
  src/HTML/makeHtml.go
  src/HTML/scripts/script.go
  src/js/graphing/blips.js
  src/js/graphing/components/banner.js
  src/js/graphing/components/buttons.js
  src/js/graphing/components/quadrantSubnav.js
  src/js/graphing/components/quadrantTables.js
  src/js/graphing/components/quadrants.js
  src/js/graphing/components/search.js
  src/js/graphing/config.js
  src/js/graphing/pdfPage.js
  src/js/graphing/radar.js
  src/js/models/blip.js
  src/js/models/quadrant.js
  src/js/models/radar.js
  src/js/models/ring.js
  src/js/remakeJS.js
  src/js/requireConfig.js
  src/js/stylesheets/style.css
  src/js/util/autoComplete.js
  src/js/util/factory.js
  src/js/util/htmlUtil.js
  src/js/util/inputSanitizer.js
  src/js/util/mathUtils.js
  src/js/util/queryParamProcessor.js
  src/js/util/ringCalculator.js
  src/js/util/stringUtil.js
  src/js/util/urlUtils.js
Labels: refactor

#138 PR[5:13] refactor: Search autocomplete dropdown list should have improved styling in frontend
  .gitignore
  docs/dev_docs/script_file_dependencies.md
  src/HTML/css/style.css
  src/HTML/images/arrow-icon.svg
  src/HTML/images/arrow-white-icon.svg
  src/HTML/images/existing.svg
  src/HTML/images/favicon.ico
  src/HTML/images/first-quadrant-btn-bg.svg
  src/HTML/images/fourth-quadrant-btn-bg.svg
  src/HTML/images/logo.png
  src/HTML/images/new.svg
  src/HTML/images/pdf_banner.png
  src/HTML/images/radar_legend.png
  src/HTML/images/search-active-wave.svg
  src/HTML/images/search-logo-2x.svg
  src/HTML/images/second-quadrant-btn-bg.svg
  src/HTML/images/tech-radar-landing-page-wide.png
  src/HTML/images/third-quadrant-btn-bg.svg
  src/HTML/js/libraries/chance.js
  src/HTML/js/libraries/d3-collection.js
  src/HTML/js/libraries/d3-selection.js
  src/HTML/js/libraries/d3-tip.js
  src/HTML/js/libraries/d3.js
  src/HTML/js/libraries/jquery-ui.js
  src/HTML/js/libraries/jquery.js
  src/HTML/js/libraries/lodash.js
  src/HTML/js/libraries/require.js
  src/HTML/js/renderingTechRadar.js
  src/HTML/js/requireConfig.js
  src/HTML/makeHtml.go
  src/HTML/scripts/script.go
  src/js/config.js
  src/js/images/favicon.ico
  src/js/remakeJS.js
  src/js/requireConfig.js
Labels: refactor

#140 PR[5:14] feat: embed dependencies in rendering
  src/HTML/makeHtml.go
Labels: feat

#149 PR[6.3] use inteface to set the merging strategy
  .golangci.yml
  docs/dev_docs/fetcher.md
  docs/dev_docs/merger.md
  docs/dev_docs/merger_strategies.md
  docs/user_docs/add_usage.md
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/HTML/css/style.css
  src/HTML/images/existing.svg
  src/HTML/images/first-quadrant-btn-bg.svg
  src/HTML/images/fourth-quadrant-btn-bg.svg
  src/HTML/images/new.svg
  src/HTML/images/second-quadrant-btn-bg.svg
  src/HTML/images/third-quadrant-btn-bg.svg
  src/HTML/js/renderingTechRadar.js
  src/HTML/makeHtml.go
  src/Merger/Fcfs.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/Verifier/verifier.go
  src/cmd/add.go
  src/cmd/merge.go
  src/go.mod
  src/go.sum
  test/end2end_test.go
  test/integration_test.go
Labels: refactor

#154 PR[6:8] feat: CLI can facilitate adding elements...
  docs/user_docs/add_usage.md
  src/cmd/add.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#158 PR[6:12] feat: CLI can facilitate removing elements
  docs/user_docs/remove_usage.md
  src/cmd/remove.go
  test/end2end_test.go
Labels: feat

#159 PR[6:13] docs: update rendering docs
  docs/dev_docs/javascript.md
  src/HTML/css/style.css
Labels: docs

#160 PR[6:14] docs: change links of gifs
  docs/user_docs/quickstart.md
Labels: docs

#161 PR[6:15] feat: merge files with links to repos
  docs/dev_docs/merger.md
  src/Merger/Fcfs.go
  src/Merger/merger.go
  src/Merger/merger_test.go
Labels: feat

#164 PR[6:17] ci: update release workflow to include exe file ext
  .github/workflows/build_test_release.yml
  ISE Guide for Testing (Desktop).pdf
  ISE_ Guide for Testing (Desktop).txt
Labels: ci

#165 PR[6:18] refactor: remove unused param
  .github/workflows/build_test_release.yml
  Makefile
  src/Merger/Fcfs.go
  src/Merger/merger_test.go
  test/integration_test.go
Labels: refactor

#168 PR[6:19] fix: fix issue where merge log didn't show picked file when logging
  .github/workflows/build_test_release.yml
  src/Merger/Fcfs.go
  src/Merger/Merge_log.txt
  test/Merge_log.txt
Labels: fix

#173 PR[6:22] ci/docs: example radar workflow
  .github/workflows/radar_workflow.yml
  ci/radar_build.go
  examples/workflows/ci/radar_build.go
  examples/workflows/github/radar_workflow.yml
  examples/workflows/workflows.md
  src/Merger/merger_test.go
Labels: docs, ci

#180 test: fix fetcher test
  .github/workflows/radar_workflow.yml
  src/Fetcher/fetcher_test.go
  test/integration_test.go
Labels: test
