Repository NovoNordisk-OpenSource/decentralized-tech-radar, pull requests merged in 2024-04, with the labels that each got.

#69 PR[3.1]chore: redo module paths
  src/HTML/html_test.go
  src/HTML/makeHtml.go
  src/go.mod
  src/main.go
  test/end2end_test.go
  test/integration_test.go
Labels: chore

#73 PR[3:2] docs/refactor: add fetcher docs and fix fetcher tests to use correct branch and repo
  .github/workflows/build_test_release.yml
  .gitignore
  .gitkeep
  ci/build_test_release.go
  ci/go.sum
  ci/test_on_push.go
  docs/dev_docs/fetcher.md
  docs/user_docs/fetcher_usage.md
  go.work.sum
  src/Fetcher/fetcher_test.go
  src/HTML/html_test.go
  src/main.go
  test/end2end_test.go
  test/go.mod
  test/go.sum
  test/integration_test.go
Labels: docs, refactor

#92 [PR4:2]feat: rendering thoughtworks radar
  docs/dev_docs/read_and_write.md
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/HTML/css/style.css
  src/HTML/html_test.go
  src/HTML/makeHtml.go
  src/SpecReader/specReader.go
  src/js/config.js
  src/js/graphing/blips.js
  src/js/graphing/components/banner.js
  src/js/graphing/components/buttons.js
  src/js/graphing/components/quadrantSubnav.js
  src/js/graphing/components/quadrantTables.js
  src/js/graphing/components/quadrants.js
  src/js/graphing/components/search.js
  src/js/graphing/config.js
  src/js/graphing/pdfPage.js
  src/js/graphing/radar.js
  src/js/images/arrow-icon.svg
  src/js/images/arrow-white-icon.svg
  src/js/images/existing.svg
  src/js/images/favicon.ico
  src/js/images/first-quadrant-btn-bg.svg
  src/js/images/fourth-quadrant-btn-bg.svg
  src/js/images/new.svg
  src/js/images/pdf_banner.png
  src/js/images/radar_legend.png
  src/js/images/search-active-wave.svg
  src/js/images/search-logo-2x.svg
  src/js/images/second-quadrant-btn-bg.svg
  src/js/images/tech-radar-landing-page-wide.png
  src/js/images/third-quadrant-btn-bg.svg
  src/js/models/blip.js
  src/js/models/quadrant.js
  src/js/models/radar.js
  src/js/models/ring.js
  src/js/requireConfig.js
  src/js/stylesheets/style.css
  src/js/util/autoComplete.js
  src/js/util/factory.js
  src/js/util/htmlUtil.js
  src/js/util/inputSanitizer.js
  src/js/util/mathUtils.js
  src/js/util/queryParamProcessor.js
  src/js/util/ringCalculator.js
  src/js/util/stringUtil.js
  src/js/util/urlUtils.js
  src/main.go
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#93 [PR4:4] feat: integrate cobra with the --merge flag/command
  src/cmd/merge.go
  test/end2end_test.go
  test/go.mod
  test/integration_test.go
Labels: feat

#94 [PR4:5] feat: integrate cobra with the --cache flag/command
  docs/dev_docs/merger.md
  docs/user_docs/merger_usage.md
  src/Fetcher/fetcher.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/cmd/merge.go
Labels: feat

#70 PR[4:6] feat: integrate cobra with the --generate flag/command
  docs/dev_docs/read_and_write.md
  docs/user_docs/generate_usage.md
  src/cmd/generate.go
Labels: feat

#95 [PR4:7] test: fix e2e tests with new cobra commands
  .gitignore
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  test/end2end_test.go
  test/integration_test.go
Labels: test

#96 PR[4:8] docs: quickstart user guide
  docs/images/quickstart_gifs/Fetch.gif
  docs/images/quickstart_gifs/Generate.gif
  docs/images/quickstart_gifs/Merging.gif
  docs/user_docs/quickstart.md
Labels: docs

#112 PR[5:1] feat: chain command bashscript
  .gitattributes
  .github/dependabot.yml
  .github/workflows/build_test_release.yml
  .gitignore
  LICENSE
  README.md
  docs/dev_docs/fetcher.md
  docs/dev_docs/merger.md
  docs/dev_docs/verifier.md
  docs/user_docs/fetcher_usage.md
  examples/csv_templates/template.csv
  scripts/dev_scripts/cmd_chainer_dev.sh
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
  src/HTML/makeHtml.go
  src/Merger/merger.go
  src/Merger/merger_test.go
  src/Verifier/verifier.go
  src/Verifier/verifier_test.go
  src/cmd/fetch.go
  src/cmd/root.go
  src/js/stylesheets/style.css
  test/end2end_test.go
  test/integration_test.go
Labels: feat

#115 PR[5:4] refactor: async fetcher
  src/Fetcher/fetcher.go
  src/Fetcher/fetcher_test.go
Labels: refactor

#135 [PR 6:1] test: Add test for Merger's duplicationRemoval
  docs/dev_docs/merger.md
  src/Merger/merger.go
  src/Merger/merger_test.go
Labels: test
